services:
  postgres:
    image: postgres:18
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dotodo
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: dotodo
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
